/**
 * Centralized SEO Configuration
 * All business data, keywords, and SEO settings in one place
 */

export const BUSINESS_INFO = {
  name: "Excel Realty Group",
  legalName: "Excel Realty Group LLC",
  phone: "(856) 555-0100",
  email: "info@excelrealtygroup.com",
  address: {
    street: "123 Main Street",
    city: "Glassboro",
    state: "NJ",
    zip: "08028",
    county: "Gloucester County",
  },
  geo: {
    latitude: 39.7029,
    longitude: -75.1118,
  },
  hours: "Mon-Fri 9AM-6PM, Sat 10AM-4PM, Sun By Appointment",
  foundingYear: 2024,
  description: "Premier real estate brokerage serving Southern New Jersey. Expert agents specializing in residential sales, rentals, and Rowan University student housing across Gloucester County and surrounding areas.",

  // Social Media
  social: {
    facebook: "https://facebook.com/excelrealtygroup",
    instagram: "https://instagram.com/excelrealtygroup",
    linkedin: "https://linkedin.com/company/excelrealtygroup",
    youtube: "https://youtube.com/@excelrealtygroup",
  },

  // Branding
  logo: "/images/logo.png",
  slogan: "Your Southern New Jersey Real Estate Experts",
};

// All 30 Southern NJ towns we serve
export const SERVICE_AREAS = [
  {
    name: "Glassboro",
    slug: "glassboro",
    county: "Gloucester County",
    zip: ["08028"],
    population: 20069,
    highlights: ["Home of Rowan University", "Growing downtown", "Affordable housing"],
    geo: { lat: 39.7029, lng: -75.1118 },
  },
  {
    name: "Marlton",
    slug: "marlton",
    county: "Burlington County",
    zip: ["08053"],
    population: 10133,
    highlights: ["Top-rated schools", "Shopping centers", "Family-friendly"],
    geo: { lat: 39.8912, lng: -74.9218 },
  },
  {
    name: "Clayton",
    slug: "clayton",
    county: "Gloucester County",
    zip: ["08312"],
    population: 8688,
    highlights: ["Small-town charm", "Near major highways", "Growing community"],
    geo: { lat: 39.6601, lng: -75.0879 },
  },
  {
    name: "Franklinville",
    slug: "franklinville",
    county: "Gloucester County",
    zip: ["08322"],
    population: 3000,
    highlights: ["Rural character", "Historic charm", "Quiet neighborhoods"],
    geo: { lat: 39.6165, lng: -75.0310 },
  },
  {
    name: "Washington Township",
    slug: "washington-township",
    county: "Gloucester County",
    zip: ["08080", "08012"],
    population: 48559,
    highlights: ["Excellent schools", "Parks and recreation", "Suburban living"],
    geo: { lat: 39.7551, lng: -75.0532 },
  },
  {
    name: "Sewell",
    slug: "sewell",
    county: "Gloucester County",
    zip: ["08080"],
    population: 3500,
    highlights: ["Family-oriented", "Shopping options", "Well-maintained homes"],
    geo: { lat: 39.7629, lng: -75.1024 },
  },
  {
    name: "Blackwood",
    slug: "blackwood",
    county: "Camden County",
    zip: ["08012"],
    population: 4692,
    highlights: ["Affordable living", "Local shops", "Community events"],
    geo: { lat: 39.8023, lng: -75.0635 },
  },
  {
    name: "Pine Hill",
    slug: "pine-hill",
    county: "Camden County",
    zip: ["08021"],
    population: 10233,
    highlights: ["Affordable housing", "Diverse community", "Lake access"],
    geo: { lat: 39.7837, lng: -74.9857 },
  },
  {
    name: "Buena",
    slug: "buena",
    county: "Atlantic County",
    zip: ["08310"],
    population: 4603,
    highlights: ["Rural setting", "Lake views", "Peaceful living"],
    geo: { lat: 39.5173, lng: -74.9293 },
  },
  {
    name: "Vineland",
    slug: "vineland",
    county: "Cumberland County",
    zip: ["08360", "08361", "08362"],
    population: 60724,
    highlights: ["Largest city in NJ by area", "Cultural diversity", "Agricultural heritage"],
    geo: { lat: 39.4862, lng: -75.0257 },
  },
  {
    name: "Mullica Hill",
    slug: "mullica-hill",
    county: "Gloucester County",
    zip: ["08062"],
    population: 3982,
    highlights: ["Historic district", "Antique shopping", "Top schools"],
    geo: { lat: 39.7243, lng: -75.2224 },
  },
  {
    name: "Monroe Township",
    slug: "monroe-township",
    county: "Gloucester County",
    zip: ["08094"],
    population: 36737,
    highlights: ["Growing community", "New developments", "Great schools"],
    geo: { lat: 39.6459, lng: -75.1413 },
  },
  {
    name: "Williamstown",
    slug: "williamstown",
    county: "Gloucester County",
    zip: ["08094"],
    population: 15567,
    highlights: ["Suburban feel", "Shopping centers", "Family-friendly"],
    geo: { lat: 39.6862, lng: -74.9921 },
  },
  {
    name: "Deptford",
    slug: "deptford",
    county: "Gloucester County",
    zip: ["08096"],
    population: 30561,
    highlights: ["Major retail hub", "Deptford Mall", "Diverse housing"],
    geo: { lat: 39.8262, lng: -75.1213 },
  },
  {
    name: "Mount Laurel",
    slug: "mount-laurel",
    county: "Burlington County",
    zip: ["08054"],
    population: 44633,
    highlights: ["Corporate headquarters", "Top schools", "Suburban lifestyle"],
    geo: { lat: 39.9340, lng: -74.8910 },
  },
  {
    name: "Evesham",
    slug: "evesham",
    county: "Burlington County",
    zip: ["08053"],
    population: 45538,
    highlights: ["Top-rated schools", "Parks and trails", "Safe neighborhoods"],
    geo: { lat: 39.8601, lng: -74.8879 },
  },
  {
    name: "Lindenwold",
    slug: "lindenwold",
    county: "Camden County",
    zip: ["08021"],
    population: 17288,
    highlights: ["PATCO station", "Affordable housing", "Diverse community"],
    geo: { lat: 39.8243, lng: -74.9971 },
  },
  {
    name: "Delran",
    slug: "delran",
    county: "Burlington County",
    zip: ["08075"],
    population: 16896,
    highlights: ["River access", "Parks and recreation", "Small-town feel"],
    geo: { lat: 40.0187, lng: -74.9532 },
  },
  {
    name: "Moorestown",
    slug: "moorestown",
    county: "Burlington County",
    zip: ["08057"],
    population: 20726,
    highlights: ["Historic downtown", "Top schools", "Affluent community"],
    geo: { lat: 39.9688, lng: -74.9488 },
  },
  {
    name: "Medford",
    slug: "medford",
    county: "Burlington County",
    zip: ["08055"],
    population: 23033,
    highlights: ["Historic village", "Excellent schools", "Lakes and parks"],
    geo: { lat: 39.8651, lng: -74.8188 },
  },
  {
    name: "Willingboro",
    slug: "willingboro",
    county: "Burlington County",
    zip: ["08046"],
    population: 31862,
    highlights: ["Affordable housing", "Community programs", "Parks and recreation"],
    geo: { lat: 40.0279, lng: -74.8693 },
  },
  {
    name: "Mount Holly",
    slug: "mount-holly",
    county: "Burlington County",
    zip: ["08060"],
    population: 9536,
    highlights: ["Historic county seat", "Rancocas Creek", "Victorian architecture"],
    geo: { lat: 39.9929, lng: -74.7879 },
  },
  {
    name: "Berlin",
    slug: "berlin",
    county: "Camden County",
    zip: ["08009"],
    population: 7588,
    highlights: ["Small-town charm", "Community events", "Affordable living"],
    geo: { lat: 39.7912, lng: -74.9288 },
  },
  {
    name: "West Berlin",
    slug: "west-berlin",
    county: "Camden County",
    zip: ["08091"],
    population: 5357,
    highlights: ["Quiet community", "Local businesses", "Family neighborhoods"],
    geo: { lat: 39.8132, lng: -74.9293 },
  },
  {
    name: "Woodbury",
    slug: "woodbury",
    county: "Gloucester County",
    zip: ["08096"],
    population: 10174,
    highlights: ["County seat", "Historic downtown", "Cultural center"],
    geo: { lat: 39.8387, lng: -75.1527 },
  },
  {
    name: "Pitman",
    slug: "pitman",
    county: "Gloucester County",
    zip: ["08071"],
    population: 8957,
    highlights: ["Dry town", "Grove concerts", "Close to Rowan"],
    geo: { lat: 39.7332, lng: -75.1313 },
  },
  {
    name: "Swedesboro",
    slug: "swedesboro",
    county: "Gloucester County",
    zip: ["08085"],
    population: 2584,
    highlights: ["Historic Swedish settlement", "Small-town feel", "Growing area"],
    geo: { lat: 39.7476, lng: -75.3105 },
  },
  {
    name: "Paulsboro",
    slug: "paulsboro",
    county: "Gloucester County",
    zip: ["08066"],
    population: 5881,
    highlights: ["Riverfront community", "Industrial history", "Affordable housing"],
    geo: { lat: 39.8301, lng: -75.2410 },
  },
  {
    name: "Elk Township",
    slug: "elk-township",
    county: "Gloucester County",
    zip: ["08343"],
    population: 4216,
    highlights: ["Rural character", "Agricultural land", "Quiet living"],
    geo: { lat: 39.6301, lng: -75.4324 },
  },
  {
    name: "Newfield",
    slug: "newfield",
    county: "Gloucester County",
    zip: ["08344"],
    population: 1553,
    highlights: ["Small borough", "Community spirit", "Historic homes"],
    geo: { lat: 39.5507, lng: -75.0118 },
  },
];

// Primary service offerings
export const SERVICES = [
  {
    name: "Buy a Home",
    slug: "buy",
    description: "Find your dream home in Southern New Jersey with expert guidance",
    icon: "🏡",
  },
  {
    name: "Sell Your Home",
    slug: "sell",
    description: "Get top dollar for your property with our proven selling strategies",
    icon: "💰",
  },
  {
    name: "Rentals & Property Management",
    slug: "rentals",
    description: "Quality rental properties and comprehensive property management services",
    icon: "🔑",
  },
  {
    name: "Rowan University Student Housing",
    slug: "rowan-housing",
    description: "Specialized student housing services for Rowan University students and landlords",
    icon: "🎓",
  },
  {
    name: "Investment Properties",
    slug: "investment",
    description: "Build wealth through strategic real estate investments",
    icon: "📈",
  },
];

// Rowan University specific data
export const ROWAN_DATA = {
  name: "Rowan University",
  location: "Glassboro, NJ",
  students: 19600,
  established: 1923,
  campuses: ["Glassboro", "Camden", "Stratford"],
  housingDemand: "High",
  peakLeasingMonths: ["October", "November", "January", "February"],
  averageRent: {
    studio: "$800-1000",
    oneBed: "$900-1200",
    twoBed: "$1200-1600",
    threeBed: "$1500-2100",
    fourBed: "$1800-2500",
    perRoom: "$500-700",
  },
  popularNeighborhoods: [
    "Downtown Glassboro",
    "Near Campus (Whitney Avenue area)",
    "Pitman (adjacent town)",
    "Rowan Boulevard",
  ],
};

// SEO Keywords by category
export const KEYWORDS = {
  primary: [
    "real estate agent southern new jersey",
    "homes for sale gloucester county nj",
    "rowan university student housing",
    "glassboro real estate",
    "buy house southern nj",
    "sell house fast nj",
  ],

  byTown: SERVICE_AREAS.map(town => ({
    town: town.name,
    keywords: [
      `${town.name.toLowerCase()} real estate`,
      `homes for sale ${town.name.toLowerCase()} nj`,
      `${town.name.toLowerCase()} real estate agent`,
      `buy house ${town.name.toLowerCase()}`,
      `sell house ${town.name.toLowerCase()}`,
      `${town.name.toLowerCase()} rentals`,
      `apartments ${town.name.toLowerCase()} nj`,
    ],
  })),

  rowan: [
    "rowan university off campus housing",
    "rowan student apartments",
    "rentals near rowan university",
    "rowan university rental specialist",
    "student housing glassboro nj",
    "rowan housing guide",
    "apartments near rowan",
    "rowan off campus rentals",
  ],

  longTail: [
    "how to sell my house fast in {town}",
    "best real estate agent in {town}",
    "what is my home worth in {town}",
    "moving to {town} nj guide",
    "{town} school district ratings",
    "cost of living in {town} nj",
  ],
};

// Default metadata
export const DEFAULT_METADATA = {
  siteName: BUSINESS_INFO.name,
  siteUrl: "https://excel-realty.com", // Update with actual domain
  defaultTitle: `${BUSINESS_INFO.name} | Southern NJ Real Estate Experts`,
  defaultDescription: "Premier real estate services in Southern New Jersey. Specializing in residential sales, rentals, and Rowan University student housing across 30+ towns in Gloucester, Burlington, Camden, and Atlantic counties.",
  keywords: [
    "southern new jersey real estate",
    "gloucester county homes",
    "rowan university housing",
    "nj real estate agent",
    "buy sell rent nj",
  ],
  ogImage: "/images/og-image.jpg",
  twitterHandle: "@excelrealty",
};
